export const CREATE_WALLET = 'CREATE_WALLET';
export const CREATE_WALLET_ENCRYPTED = 'CREATE_WALLET_ENCRYPTED';
export const IMPORT_WALLET = 'IMPORT_WALLET';
export const REMOVE_MNEMONIC = 'REMOVE_MNEMONIC';
